-- MySQL Script generated by MySQL Workbench
-- Thu May  4 09:35:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infood
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `infood` ;

-- -----------------------------------------------------
-- Schema infood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infood` DEFAULT CHARACTER SET utf8 ;
USE `infood` ;

-- -----------------------------------------------------
-- Table `infood`.`nutriment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`nutriment` ;

CREATE TABLE IF NOT EXISTS `infood`.`nutriment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`generic_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`generic_name` ;

CREATE TABLE IF NOT EXISTS `infood`.`generic_name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_generic_name_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment` (
  `id_aliment` CHAR(30) NOT NULL,
  `name_aliment` VARCHAR(250) NULL,
  `last_modification_aliment` DATETIME NULL,
  `ingredients_aliment` VARCHAR(5000) NULL,
  `generic_name_id` INT NULL,
  `grade_nutriment` ENUM('A', 'B', 'C', 'D', 'E', 'F') NULL,
  `quantity` VARCHAR(30) NULL,
  `serving_size` VARCHAR(200) NULL,
  PRIMARY KEY (`id_aliment`),
  INDEX `fk_aliment_nom_generique1_idx` (`generic_name_id` ASC),
  UNIQUE INDEX `id_aliment_UNIQUE` (`id_aliment` ASC),
  UNIQUE INDEX `generic_name_id_UNIQUE` (`generic_name_id` ASC),
  CONSTRAINT `fk_aliment_nom_generique1`
    FOREIGN KEY (`generic_name_id`)
    REFERENCES `infood`.`generic_name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`additive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`additive` ;

CREATE TABLE IF NOT EXISTS `infood`.`additive` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_additive_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_nutriment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_nutriment` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_nutriment` (
  `aliment_id_aliment` INT NOT NULL,
  `nutriment_id_nutriments` INT NOT NULL,
  `nutriment_quantity` FLOAT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `nutriment_id_nutriments`),
  INDEX `fk_aliment_has_nutriment_nutriment1_idx` (`nutriment_id_nutriments` ASC),
  INDEX `fk_aliment_has_nutriment_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_nutriment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_nutriment_nutriment1`
    FOREIGN KEY (`nutriment_id_nutriments`)
    REFERENCES `infood`.`nutriment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`nutriment_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`nutriment_level` ;

CREATE TABLE IF NOT EXISTS `infood`.`nutriment_level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_nutriment_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_additive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_additive` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_additive` (
  `aliment_id_aliment` INT NOT NULL,
  `additive_id_additive` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `additive_id_additive`),
  INDEX `fk_aliment_has_additif1_additif1_idx` (`additive_id_additive` ASC),
  INDEX `fk_aliment_has_additif1_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_additif1_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_additif1_additif1`
    FOREIGN KEY (`additive_id_additive`)
    REFERENCES `infood`.`additive` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_nutriment_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_nutriment_level` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_nutriment_level` (
  `aliment_id_aliment` INT NOT NULL,
  `nutriment_level_id_nutriment` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `nutriment_level_id_nutriment`),
  INDEX `fk_aliment_has_nutriment_niveau_nutriment_niveau1_idx` (`nutriment_level_id_nutriment` ASC),
  INDEX `fk_aliment_has_nutriment_niveau_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_nutriment_niveau_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_nutriment_niveau_nutriment_niveau1`
    FOREIGN KEY (`nutriment_level_id_nutriment`)
    REFERENCES `infood`.`nutriment_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`user` ;

CREATE TABLE IF NOT EXISTS `infood`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(15) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `height` SMALLINT NULL,
  `weight` SMALLINT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`grade` ;

CREATE TABLE IF NOT EXISTS `infood`.`grade` (
  `id_grade` INT NOT NULL,
  `name_grade` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_grade`),
  UNIQUE INDEX `id_grade_UNIQUE` (`id_grade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`brand` ;

CREATE TABLE IF NOT EXISTS `infood`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_brand_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_brand` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_brand` (
  `aliment_id_aliment` INT NOT NULL,
  `brand_id_brand` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `brand_id_brand`),
  INDEX `fk_aliment_has_marques_marques1_idx` (`brand_id_brand` ASC),
  INDEX `fk_aliment_has_marques_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_marques_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_marques_marques1`
    FOREIGN KEY (`brand_id_brand`)
    REFERENCES `infood`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`packaging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`packaging` ;

CREATE TABLE IF NOT EXISTS `infood`.`packaging` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_packaging_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_packaging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_packaging` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_packaging` (
  `aliment_id_aliment` INT NOT NULL,
  `packaging_id_packaging` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `packaging_id_packaging`),
  INDEX `fk_aliment_has_packaging_packaging1_idx` (`packaging_id_packaging` ASC),
  INDEX `fk_aliment_has_packaging_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_packaging_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_packaging_packaging1`
    FOREIGN KEY (`packaging_id_packaging`)
    REFERENCES `infood`.`packaging` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`manufacturing_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`manufacturing_place` ;

CREATE TABLE IF NOT EXISTS `infood`.`manufacturing_place` (
  `id_manufacturing_place` INT NOT NULL AUTO_INCREMENT,
  `name_manufacturing_place` VARCHAR(45) NULL,
  `mother_place` INT NULL,
  PRIMARY KEY (`id_manufacturing_place`),
  UNIQUE INDEX `id_manufacturing_place_UNIQUE` (`id_manufacturing_place` ASC),
  INDEX `fk_manufacturing_place_manufacturing_place1_idx` (`mother_place` ASC),
  CONSTRAINT `fk_manufacturing_place_manufacturing_place1`
    FOREIGN KEY (`mother_place`)
    REFERENCES `infood`.`manufacturing_place` (`id_manufacturing_place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_manufacturing_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_manufacturing_place` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_manufacturing_place` (
  `aliment_id_aliment` INT NOT NULL,
  `manufacturing_place_id_manufacturing_place` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `manufacturing_place_id_manufacturing_place`),
  INDEX `fk_lieu_fabrications_has_aliment_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_lieu_fabrications_has_aliment_lieu_fabrications1_idx` (`manufacturing_place_id_manufacturing_place` ASC),
  CONSTRAINT `fk_lieu_fabrications_has_aliment_lieu_fabrications1`
    FOREIGN KEY (`manufacturing_place_id_manufacturing_place`)
    REFERENCES `infood`.`manufacturing_place` (`id_manufacturing_place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieu_fabrications_has_aliment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`keywords` ;

CREATE TABLE IF NOT EXISTS `infood`.`keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_keywords_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_keywords` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_keywords` (
  `aliment_id_aliment` INT NOT NULL,
  `keywords_id_keywords` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `keywords_id_keywords`),
  INDEX `fk_keywords_has_aliment_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_keywords_has_aliment_keywords1_idx` (`keywords_id_keywords` ASC),
  CONSTRAINT `fk_keywords_has_aliment_keywords1`
    FOREIGN KEY (`keywords_id_keywords`)
    REFERENCES `infood`.`keywords` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keywords_has_aliment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`allergen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`allergen` ;

CREATE TABLE IF NOT EXISTS `infood`.`allergen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(25) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_allergen_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_allergen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_allergen` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_allergen` (
  `aliment_id_aliment` INT NOT NULL,
  `allergene_id_allergen` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `allergene_id_allergen`),
  INDEX `fk_allergene_has_aliment_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_allergene_has_aliment_allergene1_idx` (`allergene_id_allergen` ASC),
  CONSTRAINT `fk_allergene_has_aliment_allergene1`
    FOREIGN KEY (`allergene_id_allergen`)
    REFERENCES `infood`.`allergen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_allergene_has_aliment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`Comments` ;

CREATE TABLE IF NOT EXISTS `infood`.`Comments` (
  `text_comment` TEXT NOT NULL,
  `date_comment` TIME NOT NULL,
  `aliment_id_aliment` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `user_id_user`),
  INDEX `fk_Commentaires_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_Comments_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_Commentaires_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`Notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`Notes` ;

CREATE TABLE IF NOT EXISTS `infood`.`Notes` (
  `note` TINYINT NOT NULL,
  `aliment_id_aliment` INT NOT NULL,
  `date_note` TIME NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `user_id_user`),
  INDEX `fk_Notes_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_Notes_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_Notes_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notes_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`pic_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`pic_name` ;

CREATE TABLE IF NOT EXISTS `infood`.`pic_name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_pic_name_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`size` ;

CREATE TABLE IF NOT EXISTS `infood`.`size` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_size_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_pic_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_pic_name` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_pic_name` (
  `aliment_id_aliment` INT NOT NULL,
  `pic_name_id_pic_name` INT NOT NULL,
  `size_id_size` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `pic_name_id_pic_name`, `size_id_size`),
  INDEX `fk_nom_image_has_aliment_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_nom_image_has_aliment_nom_image1_idx` (`pic_name_id_pic_name` ASC),
  INDEX `fk_nom_image_has_aliment_taille1_idx` (`size_id_size` ASC),
  CONSTRAINT `fk_nom_image_has_aliment_nom_image1`
    FOREIGN KEY (`pic_name_id_pic_name`)
    REFERENCES `infood`.`pic_name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nom_image_has_aliment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nom_image_has_aliment_taille1`
    FOREIGN KEY (`size_id_size`)
    REFERENCES `infood`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`categorie` ;

CREATE TABLE IF NOT EXISTS `infood`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_categorie_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_categorie` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_categorie` (
  `aliment_id_aliment` INT NOT NULL,
  `categorie_id_categorie` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `categorie_id_categorie`),
  INDEX `fk_categories_has_aliment1_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_categories_has_aliment1_categories1_idx` (`categorie_id_categorie` ASC),
  CONSTRAINT `fk_categories_has_aliment1_categories1`
    FOREIGN KEY (`categorie_id_categorie`)
    REFERENCES `infood`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_aliment1_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`categorie_has_categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`categorie_has_categorie` ;

CREATE TABLE IF NOT EXISTS `infood`.`categorie_has_categorie` (
  `categorie_id_categorie` INT NOT NULL,
  `sub_id_categorie` INT NOT NULL,
  INDEX `fk_categorie_has_categorie_categorie2_idx` (`sub_id_categorie` ASC),
  INDEX `fk_categorie_has_categorie_categorie1_idx` (`categorie_id_categorie` ASC),
  PRIMARY KEY (`categorie_id_categorie`, `sub_id_categorie`),
  CONSTRAINT `fk_categorie_has_categorie_categorie1`
    FOREIGN KEY (`categorie_id_categorie`)
    REFERENCES `infood`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorie_has_categorie_categorie2`
    FOREIGN KEY (`sub_id_categorie`)
    REFERENCES `infood`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`categorie_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`categorie_language` ;

CREATE TABLE IF NOT EXISTS `infood`.`categorie_language` (
  `id_categorie_language` INT NOT NULL AUTO_INCREMENT,
  `tag_categorie_language` CHAR(2) NULL,
  PRIMARY KEY (`id_categorie_language`),
  UNIQUE INDEX `id_language_UNIQUE` (`id_categorie_language` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`categorie_translated`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`categorie_translated` ;

CREATE TABLE IF NOT EXISTS `infood`.`categorie_translated` (
  `categorie_id_categorie` INT NOT NULL,
  `translation` VARCHAR(45) NULL,
  `language_id_language` INT NOT NULL,
  PRIMARY KEY (`categorie_id_categorie`),
  INDEX `fk_categorie_translated_language1_idx` (`language_id_language` ASC),
  INDEX `fk_categorie_translated_categorie1_idx` (`categorie_id_categorie` ASC),
  CONSTRAINT `fk_categorie_translated_language1`
    FOREIGN KEY (`language_id_language`)
    REFERENCES `infood`.`categorie_language` (`id_categorie_language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorie_translated_categorie1`
    FOREIGN KEY (`categorie_id_categorie`)
    REFERENCES `infood`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `infood`.`ingredient` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idingredient_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_ingredient` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_ingredient` (
  `aliment_id_aliment` INT NOT NULL,
  `ingredient_id_ingredient` INT NOT NULL,
  PRIMARY KEY (`aliment_id_aliment`, `ingredient_id_ingredient`),
  INDEX `fk_ingredient_has_aliment_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_ingredient_has_aliment_ingredient1_idx` (`ingredient_id_ingredient` ASC),
  CONSTRAINT `fk_ingredient_has_aliment_ingredient1`
    FOREIGN KEY (`ingredient_id_ingredient`)
    REFERENCES `infood`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredient_has_aliment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`ingredient_has_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`ingredient_has_ingredient` ;

CREATE TABLE IF NOT EXISTS `infood`.`ingredient_has_ingredient` (
  `ingredient_id_ingredient` INT NOT NULL,
  `ingredient_id_ingredient1` INT NOT NULL,
  PRIMARY KEY (`ingredient_id_ingredient`, `ingredient_id_ingredient1`),
  INDEX `fk_ingredient_has_ingredient_ingredient2_idx` (`ingredient_id_ingredient1` ASC),
  INDEX `fk_ingredient_has_ingredient_ingredient1_idx` (`ingredient_id_ingredient` ASC),
  CONSTRAINT `fk_ingredient_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id_ingredient`)
    REFERENCES `infood`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredient_has_ingredient_ingredient2`
    FOREIGN KEY (`ingredient_id_ingredient1`)
    REFERENCES `infood`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`unwanted_aliment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`unwanted_aliment` ;

CREATE TABLE IF NOT EXISTS `infood`.`unwanted_aliment` (
  `user_id_user` INT NOT NULL,
  `aliment_id_aliment` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `aliment_id_aliment`),
  INDEX `fk_user_has_aliment_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_user_has_aliment_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_user_has_aliment_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_aliment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`grade_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`grade_user` ;

CREATE TABLE IF NOT EXISTS `infood`.`grade_user` (
  `user_id_user` INT NOT NULL,
  `grade_id_grade` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `grade_id_grade`),
  INDEX `fk_user_has_grade_grade1_idx` (`grade_id_grade` ASC),
  INDEX `fk_user_has_grade_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_user_has_grade_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_grade_grade1`
    FOREIGN KEY (`grade_id_grade`)
    REFERENCES `infood`.`grade` (`id_grade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
