-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 16:04:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infood
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `infood` ;

-- -----------------------------------------------------
-- Schema infood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infood` DEFAULT CHARACTER SET utf8mb4 ;
USE `infood` ;

-- -----------------------------------------------------
-- Table `infood`.`nutriment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`nutriment` ;

CREATE TABLE IF NOT EXISTS `infood`.`nutriment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`generic_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`generic_name` ;

CREATE TABLE IF NOT EXISTS `infood`.`generic_name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_generic_name_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment` (
  `id_aliment` VARCHAR(41) NOT NULL,
  `name_aliment` VARCHAR(250) NULL,
  `last_modification_aliment` DATETIME NULL,
  `ingredients_aliment` VARCHAR(5000) NULL,
  `generic_name_id` INT NULL,
  `grade_nutriment` ENUM('A', 'B', 'C', 'D', 'E', 'F') NULL,
  `quantity` VARCHAR(1000) NULL,
  `serving_size` VARCHAR(1000) NULL,
  INDEX `fk_aliment_nom_generique1_idx` (`generic_name_id` ASC),
  UNIQUE INDEX `id_aliment_UNIQUE` (`id_aliment` ASC),
  PRIMARY KEY (`id_aliment`),
  CONSTRAINT `fk_aliment_nom_generique1`
    FOREIGN KEY (`generic_name_id`)
    REFERENCES `infood`.`generic_name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`additives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`additives` ;

CREATE TABLE IF NOT EXISTS `infood`.`additives` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `name` VARCHAR(3000) NULL,
  `products` VARCHAR(3000) NULL,
  `url` VARCHAR(3000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_nutriment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_nutriment` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_nutriment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `nutriment_id_nutriment` INT NOT NULL,
  `nutriment_quantity` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliment_has_nutriment_nutriment1_idx` (`nutriment_id_nutriment` ASC),
  INDEX `fk_aliment_has_nutriment_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_nutriment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_nutriment_nutriment1`
    FOREIGN KEY (`nutriment_id_nutriment`)
    REFERENCES `infood`.`nutriment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`user` ;

CREATE TABLE IF NOT EXISTS `infood`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(15) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `height` SMALLINT NULL,
  `weight` SMALLINT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`grade` ;

CREATE TABLE IF NOT EXISTS `infood`.`grade` (
  `id_grade` INT NOT NULL,
  `name_grade` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_grade`),
  UNIQUE INDEX `id_grade_UNIQUE` (`id_grade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`manufacturing_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`manufacturing_place` ;

CREATE TABLE IF NOT EXISTS `infood`.`manufacturing_place` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_manufacturing_place_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_manufacturing_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_manufacturing_place` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_manufacturing_place` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `manufacturing_place_id_manufacturing_place` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lieu_fabrications_has_aliment_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_lieu_fabrications_has_aliment_lieu_fabrications1_idx` (`manufacturing_place_id_manufacturing_place` ASC),
  CONSTRAINT `fk_lieu_fabrications_has_aliment_lieu_fabrications1`
    FOREIGN KEY (`manufacturing_place_id_manufacturing_place`)
    REFERENCES `infood`.`manufacturing_place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieu_fabrications_has_aliment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`comments` ;

CREATE TABLE IF NOT EXISTS `infood`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `text_comment` TEXT NOT NULL,
  `date_comment` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Commentaires_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_Comments_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_Commentaires_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`Notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`Notes` ;

CREATE TABLE IF NOT EXISTS `infood`.`Notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `note` TINYINT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Notes_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_Notes_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_Notes_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notes_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`unwanted_aliment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`unwanted_aliment` ;

CREATE TABLE IF NOT EXISTS `infood`.`unwanted_aliment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_aliment_aliment1_idx` (`aliment_id_aliment` ASC),
  INDEX `fk_user_has_aliment_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_user_has_aliment_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_aliment_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`grade_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`grade_user` ;

CREATE TABLE IF NOT EXISTS `infood`.`grade_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id_user` INT NOT NULL,
  `grade_id_grade` INT NOT NULL,
  INDEX `fk_user_has_grade_grade1_idx` (`grade_id_grade` ASC),
  INDEX `fk_user_has_grade_user1_idx` (`user_id_user` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_grade_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_grade_grade1`
    FOREIGN KEY (`grade_id_grade`)
    REFERENCES `infood`.`grade` (`id_grade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`bdd_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`bdd_status` ;

CREATE TABLE IF NOT EXISTS `infood`.`bdd_status` (
  `updating` TINYINT NULL,
  `progress` FLOAT NULL)
ENGINE = InnoDB
COMMENT = 's';


-- -----------------------------------------------------
-- Table `infood`.`allergens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`allergens` ;

CREATE TABLE IF NOT EXISTS `infood`.`allergens` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `name` VARCHAR(3000) NULL,
  `products` VARCHAR(3000) NULL,
  `url` VARCHAR(3000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`brands` ;

CREATE TABLE IF NOT EXISTS `infood`.`brands` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `name` VARCHAR(3000) NULL,
  `products` VARCHAR(3000) NULL,
  `url` VARCHAR(3000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`categories` ;

CREATE TABLE IF NOT EXISTS `infood`.`categories` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `name` VARCHAR(3000) NULL,
  `products` VARCHAR(3000) NULL,
  `url` VARCHAR(3000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `infood`.`ingredients` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(900) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `name` VARCHAR(3000) NULL,
  `products` VARCHAR(3000) NULL,
  `url` VARCHAR(3000) NULL,
  `image` VARCHAR(3000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`labels` ;

CREATE TABLE IF NOT EXISTS `infood`.`labels` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `name` VARCHAR(3000) NULL,
  `products` VARCHAR(3000) NULL,
  `url` VARCHAR(3000) NULL,
  `image` VARCHAR(3000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`packaging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`packaging` ;

CREATE TABLE IF NOT EXISTS `infood`.`packaging` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `name` VARCHAR(3000) NULL,
  `products` VARCHAR(3000) NULL,
  `url` VARCHAR(3000) NULL,
  `image` VARCHAR(3000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`traces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`traces` ;

CREATE TABLE IF NOT EXISTS `infood`.`traces` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `name` VARCHAR(3000) NULL,
  `products` VARCHAR(3000) NULL,
  `url` VARCHAR(3000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_additives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_additives` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_additives` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `additives_num` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliment_has_additives_additives1_idx` (`additives_num` ASC),
  INDEX `fk_aliment_has_additives_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_additives_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_additives_additives1`
    FOREIGN KEY (`additives_num`)
    REFERENCES `infood`.`additives` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_allergens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_allergens` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_allergens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `allergens_num` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliment_has_allergens_allergens1_idx` (`allergens_num` ASC),
  INDEX `fk_aliment_has_allergens_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_allergens_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_allergens_allergens1`
    FOREIGN KEY (`allergens_num`)
    REFERENCES `infood`.`allergens` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_brands` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `brands_num` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliment_has_brands_brands1_idx` (`brands_num` ASC),
  INDEX `fk_aliment_has_brands_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_brands_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_brands_brands1`
    FOREIGN KEY (`brands_num`)
    REFERENCES `infood`.`brands` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_categories` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `categories_num` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliment_has_categories_categories1_idx` (`categories_num` ASC),
  INDEX `fk_aliment_has_categories_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_categories_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_categories_categories1`
    FOREIGN KEY (`categories_num`)
    REFERENCES `infood`.`categories` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_ingredients` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `ingredients_num` INT NOT NULL,
  INDEX `fk_aliment_has_ingredients_ingredients1_idx` (`ingredients_num` ASC),
  INDEX `fk_aliment_has_ingredients_aliment1_idx` (`aliment_id_aliment` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_aliment_has_ingredients_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredients_num`)
    REFERENCES `infood`.`ingredients` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_labels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_labels` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_labels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `labels_num` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliment_has_labels_labels1_idx` (`labels_num` ASC),
  INDEX `fk_aliment_has_labels_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_labels_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_labels_labels1`
    FOREIGN KEY (`labels_num`)
    REFERENCES `infood`.`labels` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_packaging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_packaging` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_packaging` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `packaging_num` INT NOT NULL,
  INDEX `fk_aliment_has_packaging_packaging1_idx` (`packaging_num` ASC),
  INDEX `fk_aliment_has_packaging_aliment1_idx` (`aliment_id_aliment` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_aliment_has_packaging_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_packaging_packaging1`
    FOREIGN KEY (`packaging_num`)
    REFERENCES `infood`.`packaging` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`aliment_has_traces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`aliment_has_traces` ;

CREATE TABLE IF NOT EXISTS `infood`.`aliment_has_traces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aliment_id_aliment` VARCHAR(41) NOT NULL,
  `traces_num` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliment_has_traces_traces1_idx` (`traces_num` ASC),
  INDEX `fk_aliment_has_traces_aliment1_idx` (`aliment_id_aliment` ASC),
  CONSTRAINT `fk_aliment_has_traces_aliment1`
    FOREIGN KEY (`aliment_id_aliment`)
    REFERENCES `infood`.`aliment` (`id_aliment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aliment_has_traces_traces1`
    FOREIGN KEY (`traces_num`)
    REFERENCES `infood`.`traces` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infood`.`filtre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infood`.`filtre` ;

CREATE TABLE IF NOT EXISTS `infood`.`filtre` (
  `id` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  `filtre` VARCHAR(5000) NULL,
  `json` VARCHAR(5000) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_filtre_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_filtre_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `infood`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `infood`.`bdd_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `infood`;
INSERT INTO `infood`.`bdd_status` (`updating`, `progress`) VALUES (true, 0);

COMMIT;

